exports.tasksPage = function(to_do, done, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Task Management</title>
        </head>
        <body>
                <header class="w3-container" style="background-color:#000000">
                    <center><h1 style="color:white">Task Management</h1></center>
                </header>
                
                ${form()}

                ${showTasks(to_do, done)}
                `

    pagHTML += `
                <footer class="w3-container" style="background-color:#000000">
                    <h5 style="color:white">Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}




form = function(){
    pagHTML = `
    <div class="w3-container" style="background-color:#1A1A1A">
        <center><h2 style="color:white;">Task Form</h2></center>
    </div>

    <div class="w3-container" style="background-color:#1A1A1A">
    <form class="w3-container" method="POST">
        <fieldset style="border:none">
            <label style="color:white">Description</label>
            <input class="w3-input w3-round" type="text" name="description" required>
            <label style="color:white">Person(s) accountable for task</label>
            <input class="w3-input w3-round" type="text" name="master" required>
            <label style="color:white">Deadline</label>
            <input class="w3-input w3-round" type="datetime-local" name="deadline" required>
        </fieldset>
        <br/>
        <center><button class="w3-btn w3-mb-2" style="background-color:#cc0000; color:white" type="submit">Add New Task</button></center>
        <br/>
    </form>    
    </div>
`

    return pagHTML
}

showTasks = function(){
    pagHTML = `
    <div class="w3-cell-row" style="background-color:#1A1A1A">
        <div class="w3-container w3-cell w3-half" style="background-color:#bb0000">
            <center><h3 style="color:white;">To Do List</h3></center>
            <br>
            ${toDoTasks(to_do)}
            <br>
        </div>
  
        <div class="w3-container w3-green w3-cell w3-half">
            <center><h3 style="color:white;">Tasks Completed</h3></center>
            <br> 
            ${doneTasks(done)}
            <br>
        </div>
    </div>
    `
    return pagHTML
}

toDoTasks = function(tasks){
    pagHTML = `
    <ul class="w3-ul w3-card-4" style="background-color:#dd1111">
    `

    for (let i=0; i < tasks.length ; i++){
        pagHTML += `
        <li class="w3-bar w3-leftbar">
            <div class="w3-bar-item" style="color:white">
                <table>
                <td width="50%">
                    <span class="w3-large">Task: ${tasks[i].task}</span>
                    <br>
                    <span class="w3-large">Person(s) accountable for task: ${tasks[i].taskmaster}</span>
                    <br>
                    <span>Deadline: ${tasks[i].deadline}</span>
                    <table>
                        <td>
                            <form action="http://localhost:7777/delete_td_${tasks[i].id}" method="post" class="w3-container">
                                <button type="submit" class="w3-button" style="background-color:#ff0000;color:white">Delete</button>
                            </form>
                        </td>
                        <td>
                            <form action="http://localhost:7777/complete_${tasks[i].id}" method="post" class="w3-container">
                                <button type="submit" class="w3-button" style="background-color:#00cc00;color:white">Mark as Solved</button>
                            </form>
                        </td>
                    </table>
                </td>
                <td width="50%">
                    <div class="w3-container w3-right" style="background-color:#1A1A1A">
                    <form action="http://localhost:7777/edit_td_${tasks[i].id}" method="post" class="w3-container">
                        <fieldset style="border:none">
                            <label style="color:white">Description</label>
                            <input class="w3-input w3-round" type="text" name="description" value="${tasks[i].task}" required>
                            <label style="color:white">Person(s) accountable for task</label>
                            <input class="w3-input w3-round" type="text" name="master" value="${tasks[i].taskmaster}" required>
                            <label style="color:white">Deadline</label>
                            <input class="w3-input w3-round" type="datetime-local" name="deadline" value="${tasks[i].deadline}" required>
                        </fieldset>
                        <br/>
                        <center><button type="submit" class="w3-button" style="background-color:#ff9900;color:white">Edit</button></center>
                        <br/>
                    </form>    
                    </div>
                </td>
                </table>
            </div>
        </li>
        `
    }

    pagHTML += '</ul>'

    return pagHTML
}

doneTasks = function(tasks){
    pagHTML = '<ul class="w3-ul w3-card-4" style="background-color:#11dd11">'

    for (let i=0; i < tasks.length ; i++){
        pagHTML += `
        <li class="w3-bar w3-leftbar">
            <div class="w3-bar-item" style="color:white">
                <table>
                <td width="50%">
                    <span class="w3-large">Task: ${tasks[i].task}</span>
                    <br>
                    <span class="w3-large">Person(s) accountable for task: ${tasks[i].taskmaster}</span>
                    <br>
                    <span>Deadline: ${tasks[i].deadline}</span>
                    <table>
                        <td>
                        <form action="http://localhost:7777/delete_done_${tasks[i].id}" method="post" class="w3-container"">
                            <button type="submit" class="w3-button" style="background-color:#ff0000;color:white">Delete</button>
                        </form>
                        </td>
                    </table>
                </td>
                <td>
                    <div class="w3-container w3-right" style="background-color:#1A1A1A">
                    <form action="http://localhost:7777/edit_done_${tasks[i].id}" method="post" class="w3-container">
                        <fieldset style="border:none">
                            <label style="color:white">Description</label>
                            <input class="w3-input w3-round" type="text" name="description" value="${tasks[i].task}" required>
                            <label style="color:white">Person(s) accountable for task</label>
                            <input class="w3-input w3-round" type="text" name="master" value="${tasks[i].taskmaster}" required>
                            <label style="color:white">Deadline</label>
                            <input class="w3-input w3-round" type="datetime-local" name="deadline" value="${tasks[i].deadline}" required>
                        </fieldset>
                        <br/>
                        <center><button type="submit" class="w3-button" style="background-color:#ff9900;color:white">Edit</button></center>
                        <br/>
                    </form>    
                    </div>
                </td>
                </table>
            </div>
        </li>
        `
    }

    pagHTML += '</ul>'

    return pagHTML
}